name: CI Feature Workflow Java Maven

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_KEY:
        required: true

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
      SONAR_KEY: ${{ secrets.SONAR_KEY }}       
    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: ğŸ“¦ Build com Maven
        run: mvn clean install --no-transfer-progress

      - name: ğŸ§ª Lint da imagem com Hadolint
        uses: tmknom/secure-hadolint-action@v0.4.2

      #- name: Scan de vulnerabilidades com Trivy
      #  uses: aquasecurity/trivy-action@master
      #  with:
      #    image-ref: '${{ inputs.project-name }}:latest'
      #    format: 'table'
      #    exit-code: '1'

      - name: ğŸ” AnÃ¡lise Sonar
        run: mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.organization="kubernetes-labs" -Dsonar.projectKey=$SONAR_KEY
  
  open-pr:
    runs-on: ubuntu-latest
    
    needs: [build-and-analyze]
    if: ${{ success() }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Open PR to develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Merge ${{ github.ref_name }} into develop'
          body: |
            âœ… Build, Lint, Security Scan, and Sonar passed.
            ğŸ”„ Auto-generated pull request.
          draft: false


